### ISSUE TITLE
Discussing in how far we aim to standardize for efficient comparability

### ISSUE THREAD

**Issue by valentinkm** [valentinkm/AdversarialSimulation#11]
Is it sensible to standardize steps like "file storage" to have access points to back and forth swapping pre and post simulation runs?

**Comment by lkosanke** [comment]
Firstly, we agree that a lot of standardization will be adressed via using Github as a plattform as much as possible. Other standardization is naturally subject of the collaboration process. It does not have to be explicitly specified.
Additionally, we agree that troubleshooting and verification is part of execution of the simulation itself and does not require a seperate step.
