### ISSUE TITLE
How did you connect the summary within the table on notion for the first few entries?

### ISSUE THREAD

**Issue by lkosanke** [valentinkm/AdversarialSimulation#4]
Or did you just copy and paste the contents of the summaries above?

**Comment by valentinkm** [comment]
you can sync up any number of blocks in notion across location:

Drag across blocks to select content to sync, then copy (cmd/ctrl + C).
Navigate to another page and paste (cmd/ctrl + V).
Select Paste and sync. Your content now syncs across pages.

https://www.notion.so/help/synced-blocks
