### ISSUE TITLE
Discussing the contents of LK step 3 vs. VK steps 3-5

### ISSUE THREAD

**Issue by lkosanke** [valentinkm/AdversarialSimulation#9]
I combined the steps estimation method, estimand (=population value) selection and software in one step, whereas you seperated them.

**Comment by valentinkm** [comment]
I agree here to have estimation method separate from estimants as well as population level values.

**Comment by lkosanke** [comment]
Again like in #8 , we agree that the seperation per se is not important at this point, as we agree on the order.
